#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/adweb_lab3?characterEncoding=utf-8
#    username: root
#    password:
#
#    driver-class-name: com.mysql.jdbc.Driver
#
#mybatis:
#  #实体类所做包
#  type-aliases-package: com.huang.springbootdemo.model
#  #mapper.xml所在位置
#  mapper-locations: classpath:mappers/*.xml
#
#
